# Generated by Django 5.1.7 on 2025-04-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notable_films', models.CharField(max_length=100)),
                ('years_active', models.IntegerField()),
            ],
        ),
    ]
